# Generated by Django 5.2.1 on 2025-06-27 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_alter_category_options_and_more'),
        ('libraries', '0002_alter_library_options_alter_library_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPopularityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_loans', models.PositiveIntegerField(default=0, verbose_name='Toplam Ödünç Alma')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Toplam Görüntülenme')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Toplam Değerlendirme')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='Ortalama Puan')),
                ('total_recommendations', models.PositiveIntegerField(default=0, verbose_name='Toplam Öneri')),
                ('total_collections', models.PositiveIntegerField(default=0, verbose_name='Koleksiyonlarda Yer Alma')),
                ('popularity_score', models.FloatField(default=0.0, verbose_name='Popülerlik Skoru')),
                ('trending_score', models.FloatField(default=0.0, verbose_name='Trend Skoru')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='Son Hesaplama')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity_metrics', to='books.book', verbose_name='Kitap')),
            ],
            options={
                'verbose_name': 'Kitap Popülerlik Metriği',
                'verbose_name_plural': 'Kitap Popülerlik Metrikleri',
            },
        ),
        migrations.CreateModel(
            name='ReadingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('pages_read', models.PositiveIntegerField(default=0, verbose_name='Okunan Sayfa Sayısı')),
                ('reading_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Okuma Süresi (dakika)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_activities', to='books.book', verbose_name='Kitap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_activities', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Okuma Aktivitesi',
                'verbose_name_plural': 'Okuma Aktiviteleri',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LibraryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('total_books', models.PositiveIntegerField(default=0, verbose_name='Toplam Kitap Sayısı')),
                ('available_books', models.PositiveIntegerField(default=0, verbose_name='Mevcut Kitap Sayısı')),
                ('borrowed_books', models.PositiveIntegerField(default=0, verbose_name='Ödünç Verilen Kitap Sayısı')),
                ('new_loans', models.PositiveIntegerField(default=0, verbose_name='Yeni Ödünç Verme Sayısı')),
                ('returned_books', models.PositiveIntegerField(default=0, verbose_name='İade Edilen Kitap Sayısı')),
                ('overdue_books', models.PositiveIntegerField(default=0, verbose_name='Gecikmiş Kitap Sayısı')),
                ('new_members', models.PositiveIntegerField(default=0, verbose_name='Yeni Üye Sayısı')),
                ('active_members', models.PositiveIntegerField(default=0, verbose_name='Aktif Üye Sayısı')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='Ek Veriler')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='libraries.library', verbose_name='Kütüphane')),
            ],
            options={
                'verbose_name': 'Kütüphane İstatistiği',
                'verbose_name_plural': 'Kütüphane İstatistikleri',
                'ordering': ['-date'],
                'unique_together': {('library', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LibraryUsagePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('hour', models.PositiveIntegerField(choices=[(0, '00:00'), (1, '01:00'), (2, '02:00'), (3, '03:00'), (4, '04:00'), (5, '05:00'), (6, '06:00'), (7, '07:00'), (8, '08:00'), (9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00')], verbose_name='Saat')),
                ('user_count', models.PositiveIntegerField(default=0, verbose_name='Kullanıcı Sayısı')),
                ('loan_count', models.PositiveIntegerField(default=0, verbose_name='Ödünç Alma Sayısı')),
                ('return_count', models.PositiveIntegerField(default=0, verbose_name='İade Sayısı')),
                ('search_count', models.PositiveIntegerField(default=0, verbose_name='Arama Sayısı')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_patterns', to='libraries.library', verbose_name='Kütüphane')),
            ],
            options={
                'verbose_name': 'Kütüphane Kullanım Deseni',
                'verbose_name_plural': 'Kütüphane Kullanım Desenleri',
                'ordering': ['date', 'hour'],
                'unique_together': {('library', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='ReadingGoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('daily_progress', models.PositiveIntegerField(default=0, verbose_name='Günlük İlerleme')),
                ('cumulative_progress', models.PositiveIntegerField(default=0, verbose_name='Kümülatif İlerleme')),
                ('percentage_complete', models.FloatField(default=0.0, verbose_name='Tamamlanma Yüzdesi')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='books.readinggoal', verbose_name='Hedef')),
            ],
            options={
                'verbose_name': 'Hedef İlerleme Kaydı',
                'verbose_name_plural': 'Hedef İlerleme Kayıtları',
                'ordering': ['date'],
                'unique_together': {('goal', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yıl')),
                ('month', models.PositiveIntegerField(verbose_name='Ay')),
                ('books_read', models.PositiveIntegerField(default=0, verbose_name='Okunan Kitap Sayısı')),
                ('pages_read', models.PositiveIntegerField(default=0, verbose_name='Okunan Sayfa Sayısı')),
                ('reading_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Okuma Süresi (dakika)')),
                ('loans_count', models.PositiveIntegerField(default=0, verbose_name='Ödünç Alma Sayısı')),
                ('returns_count', models.PositiveIntegerField(default=0, verbose_name='İade Sayısı')),
                ('overdue_count', models.PositiveIntegerField(default=0, verbose_name='Gecikmiş İade Sayısı')),
                ('reading_preferences', models.JSONField(blank=True, null=True, verbose_name='Okuma Tercihleri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_statistics', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı İstatistiği',
                'verbose_name_plural': 'Kullanıcı İstatistikleri',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
