# Generated by Django 5.2.1 on 2025-06-27 11:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_tag_alter_book_options_alter_booknote_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.RemoveField(
            model_name='readinggoal',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='scanrecord',
            name='scan_type',
        ),
        migrations.AddField(
            model_name='bookcollection',
            name='collection_type',
            field=models.CharField(choices=[('reading_list', 'Okunacaklar Listesi'), ('favorites', 'Favoriler'), ('completed', 'Okunanlar'), ('custom', 'Özel Koleksiyon'), ('wishlist', 'İstek Listesi'), ('recommendations', 'Öneriler')], default='custom', max_length=20, verbose_name='Koleksiyon Türü'),
        ),
        migrations.AddField(
            model_name='bookcollection',
            name='color_theme',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Renk Teması'),
        ),
        migrations.AddField(
            model_name='bookcollection',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Etiketler'),
        ),
        migrations.AddField(
            model_name='bookcollectionitem',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='bookcollectionitem',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='İlerleme Yüzdesi'),
        ),
        migrations.AddField(
            model_name='bookcollectionitem',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Değerlendirme'),
        ),
        migrations.AddField(
            model_name='bookcollectionitem',
            name='reading_status',
            field=models.CharField(choices=[('not_started', 'Başlanmadı'), ('reading', 'Okunuyor'), ('completed', 'Tamamlandı'), ('paused', 'Duraklatıldı'), ('abandoned', 'Bırakıldı')], default='not_started', max_length=20, verbose_name='Okuma Durumu'),
        ),
        migrations.AddField(
            model_name='bookcollectionitem',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AddField(
            model_name='bookidentifier',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Ek Bilgiler'),
        ),
        migrations.AddField(
            model_name='bookidentifier',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Kod Resmi'),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#007bff', help_text='Hex color code', max_length=7, verbose_name='Renk'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True, verbose_name='İkon'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkarılmış'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıra'),
        ),
        migrations.AddField(
            model_name='readinggoal',
            name='categories',
            field=models.ManyToManyField(blank=True, to='books.category', verbose_name='Hedef Kategoriler'),
        ),
        migrations.AddField(
            model_name='readinggoal',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Zorluk Seviyesi'),
        ),
        migrations.AddField(
            model_name='readinggoal',
            name='reward_message',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ödül Mesajı'),
        ),
        migrations.AddField(
            model_name='readinggoal',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('paused', 'Duraklatıldı'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='active', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi'),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='scan_action',
            field=models.CharField(choices=[('view', 'Görüntüleme'), ('borrow', 'Ödünç Alma'), ('return', 'İade'), ('inventory', 'Envanter'), ('location_check', 'Konum Kontrolü')], default='view', max_length=50, verbose_name='Tarama Eylemi'),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='bookcollection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookidentifier',
            name='identifier_type',
            field=models.CharField(choices=[('barcode', 'Barkod'), ('qrcode', 'QR Kod'), ('rfid', 'RFID'), ('isbn', 'ISBN'), ('custom', 'Özel')], max_length=20, verbose_name='Tanımlayıcı Tipi'),
        ),
        migrations.AlterField(
            model_name='readingchallenge',
            name='goal_type',
            field=models.CharField(choices=[('books', 'Kitap Sayısı'), ('pages', 'Sayfa Sayısı'), ('minutes', 'Okuma Süresi (Dakika)'), ('categories', 'Farklı Kategori Sayısı'), ('authors', 'Farklı Yazar Sayısı')], max_length=20, verbose_name='Hedef Tipi'),
        ),
        migrations.AlterField(
            model_name='readinggoal',
            name='goal_type',
            field=models.CharField(choices=[('books', 'Kitap Sayısı'), ('pages', 'Sayfa Sayısı'), ('minutes', 'Okuma Süresi (Dakika)'), ('categories', 'Farklı Kategori Sayısı'), ('authors', 'Farklı Yazar Sayısı')], max_length=20, verbose_name='Hedef Tipi'),
        ),
        migrations.AlterField(
            model_name='readinggoal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BookLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raf Kodu')),
                ('section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bölüm')),
                ('floor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kat')),
                ('coordinates', models.CharField(blank=True, help_text='x,y formatında koordinat bilgisi', max_length=100, null=True, verbose_name='Koordinatlar')),
                ('last_seen_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Son Görülme Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='books.book', verbose_name='Kitap')),
                ('last_seen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Son Gören')),
            ],
            options={
                'verbose_name': 'Kitap Konumu',
                'verbose_name_plural': 'Kitap Konumları',
            },
        ),
        migrations.CreateModel(
            name='CollectionFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True, verbose_name='Takip Başlangıcı')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Bildirimler Aktif')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='books.bookcollection', verbose_name='Takip Edilen Koleksiyon')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_collections', to=settings.AUTH_USER_MODEL, verbose_name='Takip Eden')),
            ],
            options={
                'verbose_name': 'Koleksiyon Takibi',
                'verbose_name_plural': 'Koleksiyon Takipleri',
                'unique_together': {('follower', 'collection')},
            },
        ),
    ]
