# Generated by Django 5.2.1 on 2025-06-27 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBookRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('ai_based', 'AI Tabanlı'), ('user_based', 'Kullanıcı Tabanlı'), ('category_based', 'Kategori Tabanlı'), ('similar_books', 'Benzer Kitaplar'), ('trending', 'Popüler'), ('new_releases', 'Yeni Çıkanlar'), ('manual', 'Manuel')], max_length=20, verbose_name='Öneri Tipi')),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0 - 1.0 arası öneri güvenilirlik skoru', verbose_name='Güven Skoru')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Öneri Sebebi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('viewed', 'Görüntülendi'), ('liked', 'Beğenildi'), ('disliked', 'Beğenilmedi'), ('saved', 'Kaydedildi'), ('borrowed', 'Ödünç Alındı')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Görüntülenme Tarihi')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Yanıtlanma Tarihi')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Ek Bilgiler')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='books.book', verbose_name='Önerilen Kitap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kitap Önerisi',
                'verbose_name_plural': 'Kitap Önerileri',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='CategoryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, verbose_name='Ağırlık')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
            ],
            options={
                'verbose_name': 'Kategori Tercihi',
                'verbose_name_plural': 'Kategori Tercihleri',
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='UserReadingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_authors', models.JSONField(blank=True, default=list, null=True, verbose_name='Favori Yazarlar')),
                ('preferred_languages', models.JSONField(blank=True, default=list, null=True, verbose_name='Tercih Edilen Diller')),
                ('reading_speed', models.IntegerField(blank=True, null=True, verbose_name='Okuma Hızı (sayfa/saat)')),
                ('preferred_book_length', models.CharField(choices=[('short', 'Kısa (< 200 sayfa)'), ('medium', 'Orta (200-400 sayfa)'), ('long', 'Uzun (400+ sayfa)'), ('any', 'Fark Etmez')], default='any', max_length=20, verbose_name='Tercih Edilen Kitap Uzunluğu')),
                ('reading_goals', models.JSONField(blank=True, default=dict, null=True, verbose_name='Okuma Hedefleri')),
                ('last_recommendation_date', models.DateTimeField(blank=True, null=True, verbose_name='Son Öneri Tarihi')),
                ('recommendation_frequency', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('never', 'Hiç')], default='weekly', max_length=20, verbose_name='Öneri Sıklığı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('favorite_categories', models.ManyToManyField(blank=True, through='books.CategoryPreference', to='books.category', verbose_name='Favori Kategoriler')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Okuma Profili',
                'verbose_name_plural': 'Kullanıcı Okuma Profilleri',
            },
        ),
        migrations.AddField(
            model_name='categorypreference',
            name='reading_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.userreadingprofile'),
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('accuracy', 'Doğruluk'), ('relevance', 'İlgililik'), ('diversity', 'Çeşitlilik'), ('novelty', 'Yenilik'), ('general', 'Genel')], max_length=20, verbose_name='Geri Bildirim Tipi')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Değerlendirme')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='books.aibookrecommendation', verbose_name='Öneri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Öneri Geri Bildirimi',
                'verbose_name_plural': 'Öneri Geri Bildirimleri',
                'unique_together': {('user', 'recommendation', 'feedback_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='categorypreference',
            unique_together={('reading_profile', 'category')},
        ),
    ]
