# Generated by Django 5.2.2 on 2025-06-09 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç Tarihi')),
                ('due_date', models.DateTimeField(verbose_name='Son Tarih')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='İade Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='books.book', verbose_name='Kitap')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to=settings.AUTH_USER_MODEL, verbose_name='Ödünç Alan')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lent_books', to=settings.AUTH_USER_MODEL, verbose_name='Ödünç Veren')),
            ],
            options={
                'verbose_name': 'Ödünç',
                'verbose_name_plural': 'Ödünçler',
                'ordering': ['-start_date'],
            },
        ),
    ]
