# Generated by Django 5.2.2 on 2025-06-09 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kitap Adı')),
                ('author', models.CharField(max_length=255, verbose_name='Yazar')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('is_available', models.BooleanField(default=True, verbose_name='Uygunluk Durumu')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Kapak Resmi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='libraries.library', verbose_name='Kütüphane')),
            ],
            options={
                'verbose_name': 'Kitap',
                'verbose_name_plural': 'Kitaplar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Not İçeriği')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_private', models.BooleanField(default=False, verbose_name='Özel Not')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='books.book', verbose_name='Kitap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_notes', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kitap Notu',
                'verbose_name_plural': 'Kitap Notları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='İstek Tarihi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('response_at', models.DateTimeField(blank=True, null=True, verbose_name='Yanıt Tarihi')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mesaj')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='books.book', verbose_name='Kitap')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_requests', to=settings.AUTH_USER_MODEL, verbose_name='İsteyen')),
            ],
            options={
                'verbose_name': 'Kitap İsteği',
                'verbose_name_plural': 'Kitap İstekleri',
                'ordering': ['-requested_at'],
            },
        ),
    ]
