# Generated by Django 5.2.3 on 2025-06-20 13:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0002_tag_alter_book_options_alter_booknote_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'kullanıcı', 'verbose_name_plural': 'kullanıcılar'},
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Süper Yönetici'), ('library_admin', 'Kütüphane Yöneticisi'), ('reader', 'Okuyucu')], default='reader', help_text='Kullanıcı hesabının tipini belirler.', max_length=20, verbose_name='Kullanıcı Tipi'),
        ),
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255, verbose_name='Kitap Başlığı')),
                ('book_author', models.CharField(max_length=255, verbose_name='Kitap Yazarı')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('read', 'Okundu')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='books.book', verbose_name='Kitap')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Kitap Önerisi',
                'verbose_name_plural': 'Kitap Önerileri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('loan_due', 'Ödünç Alma Süresi Yaklaşıyor'), ('loan_overdue', 'Ödünç Alma Süresi Geçti'), ('book_available', 'Kitap Müsait'), ('book_reserved', 'Kitap Rezerve Edildi'), ('request_approved', 'İstek Onaylandı'), ('request_rejected', 'İstek Reddedildi'), ('new_book', 'Yeni Kitap Eklendi'), ('review_liked', 'Değerlendirmeniz Beğenildi'), ('comment_received', 'Yorumunuza Yanıt Geldi'), ('system', 'Sistem Bildirimi')], max_length=20, verbose_name='Bildirim Tipi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bağlantı')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gönderilme Tarihi')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='books.book', verbose_name='Kitap')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Kullanıcı Mesajı',
                'verbose_name_plural': 'Kullanıcı Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('blocked', 'Engellendi')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendships', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Arkadaşlık',
                'verbose_name_plural': 'Arkadaşlıklar',
                'ordering': ['-created_at'],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
