# Generated by Django 5.2.1 on 2025-06-27 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Eylemler'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Geçerlilik Tarihi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Ek Bilgiler'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=20, verbose_name='Öncelik'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('loan_due', 'Ödünç Alma Süresi Yaklaşıyor'), ('loan_overdue', 'Ödünç Alma Süresi Geçti'), ('book_available', 'Kitap Müsait'), ('book_reserved', 'Kitap Rezerve Edildi'), ('request_approved', 'İstek Onaylandı'), ('request_rejected', 'İstek Reddedildi'), ('new_book', 'Yeni Kitap Eklendi'), ('review_liked', 'Değerlendirmeniz Beğenildi'), ('comment_received', 'Yorumunuza Yanıt Geldi'), ('goal_achieved', 'Hedef Tamamlandı'), ('recommendation', 'Yeni Kitap Önerisi'), ('collection_update', 'Koleksiyon Güncellendi'), ('friend_activity', 'Arkadaş Aktivitesi'), ('system', 'Sistem Bildirimi')], max_length=20, verbose_name='Bildirim Tipi'),
        ),
    ]
